image:
  file: .gitpod.Dockerfile

#List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn start #echo 'init script' # runs during prebuild
#   command: npm -g install firebase-tools && npm install -g npm && firebase login --no-localhost && firebase serve --only hosting
